# Generated by Django 2.1.3 on 2018-11-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23)),
                ('content', models.TextField()),
                ('morese', models.IntegerField()),
                ('creart_time', models.DateTimeField()),
                ('accomplish', models.BooleanField(default=False)),
            ],
        ),
    ]
