# Generated by Django 2.1.3 on 2018-11-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20181109_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
